services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    depends_on:
      - certbot
      - gophish
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}  # Leer del .env
    networks:
      - default

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    entrypoint: /bin/sh -c "trap exit TERM; certbot certonly --webroot -w /var/www/html -d ${DOMAIN_NAME} --non-interactive --agree-tos --email ${CERTBOT_EMAIL} && while :; do certbot renew; sleep 12h & wait $${!}; done"
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}  # Leer del .env
    networks:
      - default

  gophish:
    build:
      context: ./gophish/
    container_name: gophish-prod
    restart: unless-stopped
    ports:
      - "3333:3333"
      - "8080:8080"
    volumes:
      # Persistir sólo los datos, no sobrescribir el directorio completo
      - ./gophish-data:/opt/gophish/db  # Solo la base de datos o el contenido que necesites persistir
      - ./config.json:/opt/gophish/config.json  # Asegúrate de que el config.json esté bien ubicado
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}  # Leer del .env
    networks:
      - default

networks:
  default:
    
