services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    depends_on:
      - certbot
      - gophish
    env_file:
      - .env  

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    entrypoint: /bin/sh -c "trap exit TERM; certbot certonly --webroot -w /var/www/html -d $${DOMAIN_NAME} --non-interactive --agree-tos --email $${CERTBOT_EMAIL} && while :; do certbot renew; sleep 12h & wait $${!}; done"
    env_file:
      - .env  

  gophish:
    image: gophish/gophish
    ports:
      - "3333:3333"
      - "8080:8080"
    volumes:
      - ./gophish-data:/opt/gophish
    environment:
      - ADMIN_EMAIL=$${ADMIN_EMAIL}  # Usamos la variable del .env
    restart: always
    env_file:
      - .env  