services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    depends_on:
      - certbot
      - gophish
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}  # Leer del .env
    networks:
      - default

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    entrypoint: /bin/sh -c "trap exit TERM; certbot certonly --webroot -w /var/www/html -d ${DOMAIN_NAME} --non-interactive --agree-tos --email ${CERTBOT_EMAIL} && while :; do certbot renew; sleep 12h & wait $${!}; done"
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}  # Leer del .env
    networks:
      - default

  mysql:
    image: mysql:8.4.2
    container_name: gophish-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - default
    env_file:
      - .env

  gophish:
    build:
      context: ./gophish/
    container_name: gophish-prod
    restart: unless-stopped
    ports:
      - "3333:3333"
      - "8080:8080"
    volumes:
      # Persistir sólo los datos, no sobrescribir el directorio completo
      - gophish-data:/opt/gophish/db  # Solo la base de datos o el contenido que necesites persistir
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}  # Leer del .env
    networks:
      - default
    depends_on:
      - mysql

volumes:
  mysql_data:
  gophish-data:

networks:
  default:
    
